### PR TITLE
Create awscli

### PR DESCRIPTION
**Pull request by ireaneus**
AWS Command line commands

### CODE REVIEW

**Comment by chubin** [comment]
What is the main idea behind the `awscli` page and what is the main difference
to the `aws` page that we already have?

**Comment by ireaneus** [comment]
It's an exhaustive list of all AWS CLI commands for all services. I didn't see a cheat for AWS till now, should I merge the two together?

Thanks for the quick response. Been using cheat for a long time and have my own repo for Linux cheat sheets.
GitHub.com/ireaneus/cheatsheet

David

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ireaneus** [comment]
Sorry a bit new to this.  I was pretty much testing out how to add to your repository.  I am going to close this pull request and add to the existing aws cheatsheet.

**Comment by terminalforlife** [comment]
Nice one, @ireaneus. Welcome to the fold. :P

**Pull request closed without merging**
