### PR TITLE
swift types

### PR DESCRIPTION
**Pull request by lf-araujo**
Added cheatsheet for swift types.

### CODE REVIEW

**Comment by chubin** [comment]
@lf-araujo 
Actually, we are not allowed to use materials from TutorialsPoint here:

https://www.tutorialspoint.com/about/faq.htm

> «
> Can we reuse/publish the content available on tutorialspoint.com?
> 
> Sorry, we do not allow to use our content for republishing online or to be printed for commercial purpose. But yes, you can use our content with in your Schools, Colleges, Universities, Institutes and Companies as long as it is only for internal purpose and you are keeping appropriate references to tutorialspoint.com website.
> »

That means that we have to remove this materials, 
but I will try to write some other page instead.

We should find a good cheat sheet repository for swift (better on github),
and bind it to cheat.sh (as we did it for go for example).

**Comment by lf-araujo** [comment]
Sorry, didn't see that, will write some of my own and push.

**Comment by chubin** [comment]
@lf-araujo 
It's ok! I've already rewritten the page.
Please check:
```
curl cht.sh/swift/types
```

**Comment by lf-araujo** [comment]
Great,

I will reproduce your style in the next one, do you have a style guide 
you want contributors to follow?


All the best,

lf
Em 02-08-2018 17:32, Igor Chubin escreveu:

**Comment by chubin** [comment]
@lf-araujo Hi! Sorry for the silence. I am back now,

Not yet, but there are several things that you should keep in mind:

1. All cheat sheets in the same file are separated with an empty line (that means that there should no be no empty lines inside cheat sheets);
2. All cheat sheets should use the syntax of their programming language
3. The cheat sheets should be concise

**Pull request merged**
