### PR TITLE
Scala - Added ManipulatingCollections sheet and minor tidy for DataSt…

### PR DESCRIPTION
**Pull request by CEPoole**
…ructures

### CODE REVIEW

**Comment by CEPoole** [comment]
You suggested adding another sheet so I've added the core functions to manipulate collections, using simple Lists for the examples

**Comment by chubin** [comment]
Very good! Thank you very much for the new cheat sheets.
Do you need all scala related queries to the service?
Then we could aggregate them and find the missing Scala cheat sheets?

**Comment by CEPoole** [comment]
@chubin wow. If you could provide that then I could definitely try and contribute based on what people are looking for, that would be great!

**Comment by chubin** [comment]
Here is the list.
Many of queries are almost the same, they are not grouped (though they could be),
they are shown in that form as they are received by the server (before internal processing and rewriting). Some of them are already covered by our cheat sheets and some of them are not.
A couple of queries are in French (because of translation module was broken for some time and the queries were not translated).
`weirdness` and `1line` are our standard cheat sheets available for other languages, but not available for Scala; probably we should start with them. Though I am not sure, do we have any weird things in Scala or no weird thing at all?

The rest is probably already covered by our cheat sheets, but maybe there are some topics (group of topics) that are still not covered.

I'm working currently on a new important feature, that would be extremely useful in this case: it is so called see-also feature.

The idea is to show links to related cheat sheets when giving an answer to a query.
Say you ask:

scala read file

You get this:

```scala
// Read entire file in Scala?

val lines = scala.io.Source.fromFile("file.txt").mkString

/*
 * By the way, "scala." isn't really necessary, as it's always in scope
 * anyway, and you can, of course, import io's contents, fully or
 * partially, and avoid having to prepend "io." too.
 * 
 * The above leaves the file open, however. To avoid problems, you should
 * close it like this:
 */

val source = scala.io.Source.fromFile("file.txt")
val lines = try source.mkString finally source.close()

/*
 * Another problem with the code above is that it is horrible slow due to
 * its implementation nature. For larger files one should use:
 */

source.getLines mkString "\n"

// [Daniel C. Sobral] [so/q/1284423] [cc by-sa 3.0]
```

+ you get the see also section, that looks like:

```
// See also:
// [1] scala write file [2] Scala/Files [3] scala/ref/scala.io.Source
```

In this example `[2] Scala/Files` is a cheat sheet written by hand, it is a cheat sheet from the repository.
That means that the users will use (at least they will be recommended to use) the cheat sheets from the repository even if they have distinct questions covered by cheat sheets generated on the fly.

That's why the repository cheat sheets are extremely important.

----

Appendix 1. The list of the queries

```
      9 read file
      7 reverse list
      6 function
      5 write to file
      5 scala
      5 map
      5 learn
      4 weirdness
      4 reverse a list
      4 main
      4 list
      4 implicit
      4 functions
      4 execute external program
      4 1line
      3 what is arity
      3 type infer
      3 spark
      3 sbt
      3 patternmatching
      3 parse json
      3 object
      3 monads
      3 lambda
      3 future
      3 flatmap
      3 class
      3 akka
      2 zip list
      2 write file
      3 variables
      2 val
      2 trait
      2 sort
      2 set
      2 reverse
      2 reading file
      2 read from file
      2 read
      2 random list elements
      2 quick sort
      2 play
      2 pattern matching
      2 partial
      2 parse xml
      2 option
      2 main app
      2 lists
      2 implicits
      2 groupBy map
      2 go/scala
      2 go
      2 generics
      2 Future
      2 func
      2 filter map
      2 filter
      2 file
      2 datastructures
      2 currying
      2 curry
      2 cats
      2 case
      2 a
      1 zip map
      1 zip
      1 what
      1 weridness
      1 var vs val
      1 var vs al
      1 /var/list
      1 variadic function
      1 var
      1 use config file
      1 unoin
      1 unit tests
      1 union
      1 typing
      1 typical type class 0
      1 types
      1 type function
      1 type class 0
      1 type class
      1 tutorial
      1 try catch
      1 try
      1 trie
      1 transpose list
      1 transient
      1 trait default method
      1 thread
      1 /test
      1 test
      1 tail-recursion
      1 tailrec 0
      1 tailOption
      1 tail
      1 syntax
      1 switch
      1 sum array
      1 subclass
      1 string template
      1 string
      1 spark write to parquet file
      1 spark write to parquet
      1 spark write parquet
      1 spark sort rdd
      1 spark sort
      1 spark session
      1 spark read parquet from file
      1 spark read parquet file to dataframe
      1 spark read parquet
      1 spark memory overhead
      1 spark long
      1 spark limit rdd
      1 spark limit
      1 spark datatypes longtype
      1 spark dataset
      1 spark convert dataframe to rdd
      1 sort list
      1 Some
      1 slice
      1 set array position
      1 :set
      1 seq to map
      1 Seq/create
      1 Seq
      1 seq
      1 semigroup
      1 sealed class
      1 script
      1 scala zip
      1 scalaz/EitherT
      1 scalaz
      1 scala /0/0
      1 routine
      1 require 0
      1 replace
      1 repla
      1 repl
      1 @Rein Henrichs
      1 reflection
      1 reduceleft
      1 reading files
      1 read from stdin
      1 read from mysql
      1 read from mongo
      1 rdd
      1 random string
      1 python/scala
      1 push to array
      1 print
      1 post file
      1 pointers
      1 plus equal
      1 patterns
      1 pattern match tuple 0
      1 patternMatching
      1 :/patternmatching
      1 :patternmatching
      1 pattern match if 0
      1 pattern match  0
      1 pattern match
      1 pattern
      1 partially
      1 parse
      1 packages/:lest
      1 :packages
      1 packages
      1 ouvrir un programme
      1 ouvrir un file
      1 ouvrir file
      1 option to list
      1 options
      1 Option 0
      1 Option
      1 operator
      1 open a text file
      1 new var
      1 new thread
      1 mysql connect
      1 mysql
      1 moonad
      1 monade
      1 monad
      1 mkString
      1 merge maps
      1 mark unreachable
      1 map to list
      1 mapmake
      1 map key list
      1 map a list
      1 ManipulatingFunctions
      1 Manipu
      1 manifest
      1 make http request
      1 main function
      1 macros
      1 macro
      1 ls
      1 loop array
      1 log
      1 list split
      1 list reverse
      1 list of keys in a map
      1 list comprehension
      1 List 0
      1 lis
      1 linked list
      1 leftFold
      1 left
      1 json
      1 javascript/scalanie tablic
      1 java
      1 iterate list
      1 io
      1 int to string
      1 initialise a variable
      1 inherantace
      1 infix sugar
      1 import statement
      1 implicit search order
      1 implicit
      1 Implicits
      1 implicit conversions
      1 implicit class
      1 implic
      1 if
      1 how to serialize to bytes
      1 how to serialize a object
      1 how to serialize
      1 how to do foldRigth with foldLeft 0
      1 how to do foldRight with foldLeft
      1 how to do foldLeft 0
      1 how to catch exceptions
      1 high order types
      1 high order type
      1 higher order type
      1 higher order function
      1 higher kinded types
      1 hellp
      1 hello-world
      1 hello world
      1 helloworld
      1 :hello
      1 hello
      1 hell
      1 haskell/lambda
      1 hadoop class
      1 grouped
      1 groupby map
      1 groupBy
      1 groupby
      1 go/scala funtions
      1 get array length
      1 generic tuple
      1 generics multiple
      1 get array length
      1 generic tuple
      1 generics multiple
      1 generic method tuple
      1 generic method multiple
      1 generic method
      1 generic inherantice
      1 generate random data
      1 future testing
      1 future/sequential
      1 Futures
      1 funtions
      1 funtion
      1 functor akka
      1 functor
      1 functions main
      1 functions/
      1 functions lazy
      1 functions/andthen
      1 functionN tuplen intellij
      1 functionN tuplen
      1 free monad
      1 foreach
      1 for comp
      1 forcomp
      1 forall
      1 foldRight with foldLeft 0
      1 foldleft and foldright 0
      1 foldLeft 0
      1 foldleft 0
      1 fold left
      1 flatten
      1 flatmap option
      1 flatmap example
      1 find element in list
      1 filter only
      1 filter list
      1 file read
      1 f
      1 execute program
      1 execute process
      1 execute external programm
      1 execute external
      1 either
      1 effect 0
      1 dotty
      1 dictionary
      1 define type
      1 define integer array
      1 define integer
      1 define functions
      1 define default method trait
      1 define array
      1 def
      1 declare methos
      1 declare method
      1 declare a list
      1 data types
      1 curied
      1 create class
      1 convert option to list
      1 convert json
      1 convert future of option to option of future
      1 control scructures
      1 consume from kafka
      1 concurrent dictonary
      1 concurrency
      1 compute sum of array
      1 compile file
      1 collect
      1 closure
      1 close resource
      1 close file
      1 clas
      1 check operating system
      1 catw
      1 catch_exceptions
      1 case class serialize
      1 cake pattern
      1 cake
      1 bash command
      1 backend
      1 async call
      1 async
      1 assign array position
      1 arrow
      1 arrays
      1 array loop
      1 array length
      1 array
      1 append
      1 api
      1 anyval
      1 annotation transient
      1 andthen
      1 akka stream
      1 akka http
      1 adt
      1 add to seq
      1 add to a dataframe
      1 actors
      1 actor
```

**Pull request merged**
