### PR TITLE
Added page for Cargo package manager.

### PR DESCRIPTION
**Pull request by sullivant**

### CODE REVIEW

**Comment by chubin** [comment]
@sullivant Thomas, what do you think, maybe we should add content of this page to `/cargo` too?

**Comment by sullivant** [comment]
Good catch - I naturally assumed Cargo, a tool within the Rust language, would be within Rust/Cargo and not /cargo.  However, there is indeed a /cargo page.   Blah.  That's my bad, however I can definitely see folks shooting for both.  Not to show my age, but would PPM be under PERL?  Or on its own.  

Let me submit a PR to keep the two Cargo pages synced up.  I think they are both worth it and if you'd like to replace one with the other, they'll both be ready.

**Comment by sullivant** [comment]
@chubin Igor - I have created a PR that syncs the content in sheets/_rust/Cargo with sheets/cargo.  What's your stance on where things should go?

**Comment by chubin** [comment]
@sullivant Thomas, have you seen this:

https://www.reddit.com/r/rust/comments/cm7rje/rust_language_cheat_sheet/

What do you think, probably we should fully integrate cheats.rs into cheat.sh, as one of its upstream repositories, as we did with Learn-X-in-Y for example or with other reps.

What do you say?

**Comment by sullivant** [comment]
@chubin Igor - I did see it out on the sub yesterday sometime, or this morning.  I think it's very well written and you can see the repo [here](https://github.com/ralfbiedert/cheats.rs/).  It looks like it's all contained in content/_index.md and the focus is on being visually clean for the browser/pdf.

I don't think we can automatically import it into here, as it's a bunch of divs all with a static class of "cheats" separated by lines for each section.  

I reckon we could cherry pick stuff one would want to see on the CLI through a curl of cht.sh or via the cheat.sh app.  Thoughts?

**Pull request merged**
