### PR TITLE
New Cheat Sheet

### PR DESCRIPTION
**Pull request by terminalforlife**
Just discovered this today; is awesome.

### CODE REVIEW

**Comment by chubin** [comment]
Very good command. I would also add `xinput list` and a couple of other examples

**Comment by chubin** [comment]
Did it:

https://github.com/chubin/cheat.sheets/commit/2111e67697a95ac95227102bef486c78db966fef

(specified wrong PR in the commit message)

**Comment by terminalforlife** [comment]
Oh, I'm sorry! I must have misinterpreted what you meant. I didn't realise you wanted me to actually add those things. I'd have done that right away if that had sunk in. At least it's sorted, now. Lol

**Comment by chubin** [comment]
No @terminalforlife everything is ok! Maybe you indeed misinterpreted me, but this time, not before :) What I meant, I add the things, and specified the PR number in the commit message (wanted to specify 157, but made a type and specified 158). my bad, but not a big deal. And `xinput` is a very cool tool, thank you a lot for mentioning it. Very good and useful

**Pull request merged**
