### PR TITLE
Create Solidity

### PR DESCRIPTION
**Pull request by WizardOfAus**
Add skeleton for proposed language to be added

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much for the pull request!

I've renamed `Solidity` to `_solidity` (according to our section naming rules), but the cheat sheets (as soon as they exist) will be accessible at `/solidity/`:

```
curl cht.sh/solidity/hello
```

If you want to create new solidity cheat sheets and you don't know what you should start,
I can send you the list of all queries about solidity that we've got (if there were any),
that could be a good starting point.

Also, what should be added:

* learnxiny mapping
* syntax highlighting
* server side comments
* the hello page

Please give me a sign if you want to participate.

**Comment by chubin** [comment]
Currently we had only three queries about solidity (probably from you?):

solidity/:learn
solidity/if
solidity/contract

:learn will be added by mapping learn-x-in-y, as I said above.
And `if` and `contract` seem to be good candidates
to be the first solidity cheat sheets.

-- 
Igor Chubin

**Comment by chubin** [comment]
@WizardOfAus Hi!

Support for solidity was added (server-side comments, syntax highlighting etc, Learn-X-in-Y integration).
try:

```
curl cht.sh/solidity/:learn
```

**Comment by WizardOfAus** [comment]
@chubin Hey Igor! Sorry for the late reply, was busy with some other stuff have some upcoming exams and workshops to prepare for. Great that you added the support! Will try contribute more when I have some more time :)

**Comment by chubin** [comment]
@WizardOfAus Thank you! I think that soon, after we will add several new interesting features, the project will be even more interesting for all cryptocurrencies users. Stay tuned

**Pull request merged**
