### PR TITLE
Added lse (Linux-Smart-Enumeration) script

### PR DESCRIPTION
**Pull request by hornjbl**
I've added a script that I often need to refer to my own notes for :

This is the linux-smart-enumeration, or lse script, based on enum4linux.

### CODE REVIEW

**Comment by terminalforlife** [comment]
Can you wrap the comments to keep it within 80 columns?

**Comment by hornjbl** [comment]
Will do ;-)

**Comment by terminalforlife** [comment]
Nailed it!

**Comment by hornjbl** [comment]
> Nailed it!

Apologies, I saw afterward that the 80 col limit is clearly mentioned in the docs. Should have paid more attention...

**Comment by terminalforlife** [comment]
It's okay. It was a fairly recent addition, AFAIK. I wrote the [LenChk](tests/lenchk) tester, which you can use if you want to test line length before sending a PR.

**Comment by chubin** [comment]
Please test; it should be available at `cheat.sh/lse` now.

Maybe it should be `lse.sh` and not `lse`, or other way around?
Your command must be `lse` and not `lse.sh`?

**Comment by hornjbl** [comment]
Thanks @chubin, tested and it's working.

Ah, agree, the command is lse.sh, so if you prefer the file to be named with the name and extension, I'm happy to update. 

Being new to github and collaborating on someone else's repo, do I just rename the file in my local repo, push to remote, and create a new pull request? Will it handle the rename accordingly and not just see it as a new file?

**Comment by chubin** [comment]
Yes, you can do it just as any other repository change. I already did it for you. It must be available under the new name now

**Pull request merged**
