### PR TITLE
Update convert

### PR DESCRIPTION
**Pull request by gfrein**

### CODE REVIEW

**Comment by terminalforlife** [comment]
Nice. The program from ImageMagick? Did you know that ffmpeg(1) can also convert images?

**Comment by chubin** [comment]
@terminalforlife BTW, I think that our ffmpeg cheat sheet is very shot. It has sooo many features

**Comment by terminalforlife** [comment]
@chubin Noted. ;)

**Comment by gfrein** [comment]
@terminalforlife Convert from ImageMagick, yes. Quite useful for converting a bunch of scanned documents into a single pdf. Interesting, I just looked at the ffmpeg cheat sheet - I didn't know it could convert several images to video (nice for making slideshows or stop motion videos). Thanks for the hint!

**Comment by terminalforlife** [comment]
Yup, it's awesome to make GIFs with. :)

**Comment by chubin** [comment]
`ffmpeg` is incredibly powerful. It has thousands of differene options, subcommands and modes.
I think it deserves a special cheat sheets section (`cheat.sh/ffmpeg/....`) with a separate cheat sheet for filter. What do you think?

As the first step though, we could improve the root cheat sheet `/ffmpeg`) and the most important commands there

**Comment by terminalforlife** [comment]
Agreed on all fronts, Chubin.

**Pull request merged**
