### PR TITLE
Add yq sheet

### PR DESCRIPTION
**Pull request by raymondchen625**
Added a sheet for ya, the [YAML processing tool](https://github.com/mikefarah/yq).

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This probably needs an update with 4.0.0.

**Comment by chubin** [comment]
@SuperSandro2000 Some of the commands will be changed?

**Comment by SuperSandro2000** [comment]
Baasically all of them and they are not backwards compatible. See https://mikefarah.gitbook.io/yq/v/v4.x-alpha/upgrading-from-v3

**Comment by terminalforlife** [comment]
Under the original blocks, how about adding an updated version? So that people on older versions can still have that information, and people on newer versions will understand what it was, which might be useful for scripting purposes or if they also have an older version on another machine, for whatever reason.

So:

```
# Description of old command
old command
# Description of old command with updated syntax. Include version number.
old command with updated syntax.
```

What chu fink?

**Comment by raymondchen625** [comment]
Cheat sheets are supposed to be short. I would like to only keep those only
work with the latest version. But indicating the version at the beginning
is a good idea.

**Comment by chubin** [comment]
I think that we should display the fragments which are relevant for the current (stable)
version of the program. The rest should be show only if it is requested explicitly.

Of course, to implement it, we need to:

1. make it possible to mark some blocks as applicable to some version only
2. make cheat.sh know what versions are actual at the moment.

I think, the (2) is quite useful and interesting and I have a couple of ideas how it could be implemented

**Comment by raymondchen625** [comment]
Yes, keeping all in one sheet is ideal. I imagine the markups will include
things like @since, @deprecated @removed.
For a total breaking change like yq 4, all v3 commands will have
@removed=4. Things like that.

**Pull request merged**
