### PR TITLE
Create task-spooler sheet

### PR DESCRIPTION
**Pull request by vjanssens**
This PR introduces a cheat sheet for the task-spooler program (http://manpages.ubuntu.com/manpages/xenial/man1/tsp.1.html).

### CODE REVIEW

**Comment by terminalforlife** [comment]
Would you add the header stuff? Like:

```
# task-spooler
# Description of task-spooler (official short description, if possible)

...rest of file.
```

**Comment by vjanssens** [comment]
I've added the description, thanks

**Comment by terminalforlife** [comment]
Nice.

Bit confused by this though: `tsp`

Is that the actual command? If so, make sure the file and first line is changed accordingly, otherwise it will probably confuse people. Say, for example, I'm on the terminal, cURL-ing `cheat.sh/tsp`, only to find no results, not realising it's in a different name.

...or am I misunderstanding something?

**Comment by vjanssens** [comment]
No worries @terminalforlife, i've updated the PR :)

**Comment by chubin** [comment]
@vjanssens Well done Vadiem! Thank you and sorry for the late merge

**Pull request merged**
