### PR TITLE
Fix comment length in all first-level cheat sheets

### PR DESCRIPTION
**Pull request by chubin**
*  sheets/MegaCli
*  sheets/az
*  sheets/azure
*  sheets/blktrace
*  sheets/emacs
*  sheets/exim
*  sheets/go
*  sheets/ipython
*  sheets/jq
*  sheets/nmap
*  sheets/perl
*  sheets/psql
*  sheets/redis
*  sheets/sed
*  sheets/smartctl
*  sheets/solidity
*  sheets/yq_v4

### CODE REVIEW

**Comment by chubin** [comment]
@terminalforlife Now we have only several cheat sheets in subdirectories,
that are to be fixed, and the rest is done

**Comment by terminalforlife** [comment]
Oh my Lord. I'm impressed! Thought it would take much longer. Lol Sorry if not committed much in the last couple of days. I've been working on [apt-history](https://github.com/terminalforlife/PerlProjects/blob/master/source/apt-history) (early video of it [here](https://youtu.be/NRKhxaL0kGQ)) and [this](https://www.youtube.com/watch?v=mr5VYJ75WQc) video, similar to what you asked about elsewhere on your GitHub.

**Comment by chubin** [comment]
It is an interesting tool. I think it can be very useful when it is needed to see what dependencies were installed for some new project, during a iterative "configure — compile — install dependencies — repeat " session, after the installation is finally finished. At least, I missed tool like that. (by the way, does it have a cheat sheet?)

Regarding switching colors off: sure, just use the `?T` option:

```
curl cht.sh/cp?T
```

**Comment by terminalforlife** [comment]
Wow! It was so simple to do. Thanks!

**Comment by chubin** [comment]
`curl cht.sh/:help` for more options

**Comment by terminalforlife** [comment]
I'd like to check something with you. If you're not okay with it, then I'll respect your wishes. Would you be okay with my writing and distributing a program which directly uses the files stored within your cheat.sheets repository? It's such a good resource, and I'd like to offer an alternative to the cheat.sh web interface. I would of course be only too happy to make it clear where the 'sheets' comes from. ;)

**Comment by chubin** [comment]
Sure! Just feel free to use it. As soon as the program is done, don’t forget to add a cheat sheet for it :)

**Comment by terminalforlife** [comment]
Thank you! You're a star. It's just an idea I have in mind, but now that you've given me the go-ahead, I can plan and get writing.

**Pull request merged**
