### PR TITLE
Fix Usage() & Possibly More...

### PR DESCRIPTION
**Pull request by terminalforlife**
Can't believe it took me so long to realise I borked part of the Usage(). Lol

Don't merge this yet, because I'm probably going to add more, but at least this way it's easy to see what I'm up to. I'll let you know when I'm done committing. :)

BTW, @chubin, what do you think of [this](https://www.youtube.com/watch?v=y4uceSqenoY)? Early version, but it's somewhat getting there.

### CODE REVIEW

**Comment by terminalforlife** [comment]
Okay, I'm done! Gotta sleep now. Lol

**Comment by chubin** [comment]
I like your `cheater`. It is very clean and simple, and it does the most important things.
I especially like your idea to remove the comments when the syntax highlighting is used.

It is a good alternative to the shell client (cht.sh, which is available at `https://cht.sh/:cht.sh`).

Several minor questions:

* Do you support search and subqueries?
```
curl cht.sh/btrfs~volume
curl cht.sh/snapshot
```

* Do you support programming languages queries?

```
curl cht.sh/perl/read+json
```

* I noticed the `completion` file in the video, do you have tab-completion support?
Is it `/:list`-based?

**Comment by terminalforlife** [comment]
> Do you support search and subqueries?

It supports highlighting, which is as close to searching as it gets, for now.

> Do you support programming languages queries?

Not yet.

> I noticed the completion file in the video, do you have tab-completion support?

Yeah, BASH completion is supported.

> Is it /:list-based?

I don't understand the question here.

Glad you like it. It's just the first iteration, so there's a good chance it'll get updates in the future, especially if it sees interest.

**Comment by chubin** [comment]
> Not yet. Just to ensure I understand you correctly, what do you mean here?

What I mean here: you know that cheat.sh supports not only operating systems cheat sheets, but by means of its *adapters* it can show cheat sheets for programming languages too, basically answers for (a very broad range of) coding questions. It works like this:

If you want to know how to read yaml in python (`python read yaml`),
you just ask:

`curl cheat.sh/python/read+yaml`

It fetches answers from different sources on the fly, primarily from StackOverflow in this case.

So the question was, do you wrap coding questions into cheat.sh queries too, or `cheater` is intentionally for command line tools cheat sheets only?

**Comment by terminalforlife** [comment]
That's an awesome feature of cheat.sh! Cheater, however, only handles utilities and things in, say, the 'perl' subdirectory. I had no idea cheat.sh could do so many other cool things.

**Comment by chubin** [comment]
Yes, but if `cheater` queries the cheat.sh server for that, that means that `cheater` already handles such queries. What about: `cheater perl read+yaml` or how was the syntax exactly?

**Pull request merged**
