### PR TITLE
Add Changes Mentioned in #133

### PR DESCRIPTION
**Pull request by terminalforlife**
Addressed changes suggested by @chubin in #133 PR. Refer to commit messages if I missed anything. Hope you like it. :D I took a little *too* long working on this. Lol I did add a few extra features.

### CODE REVIEW

**Comment by chubin** [comment]
Additionally to the whitelisting file, it would be good to add some in-band flag, e.g if a file contains say `lenchk=disable` it must be  skipped

**Comment by terminalforlife** [comment]
I can sort that. Would you, in cheat.sh, be willing to omit the top-most line in a file containing 'lenchk=disable', but only if it contains that file? That way your readers won't see it.

**Comment by chubin** [comment]
Thank you for the improvements in #135. I like them a lot.
Several minor remarks, as usually:

1. I noticed that the red color in the output is sometimes dark-red and sometimes light-red. Does it have some special meaning, or it is just some strange artifact?

2. Exit code (even though the test is failing, i.e. there are pages with lines longer than 80, is 0.

3. Regarding `lenchk=disable`, I would suggest scan the whole file for this line, and ignore the file if the line is found in it (like this: `grep -qrE lenck=(disable|.*,disable) "$file" && continue`). Then we could have this line anywhere in the cheat sheet, and it can be commented out with any comment style (which depends on the programming language). I would handle such line as a special case in cheat.sh, and automatically filter it out.

I propose such format:

```
# cheat.sh: [SOME_OPTIONS,]+lenchk=disable[,SOME_OPTIONS]*
```

and the `cheat.sh` line (which can contain some additional options) will be automatically filtered.

Maybe @chrisallenlane will have some similar special line too, so it would be possible to configure such special mode-line for each adapter.

**Comment by terminalforlife** [comment]
Sorry, I forgot all about the exit status thing. Cooking at the minute, but will get to that and hopefully other stuff later tonight or tomorrow.

So, the proposed format...

Are you saying there's going to be a `cheat.sh: .*` line on potentially any file, much like the Vim modeline? And if so, `lenchk=disable` is one of many comma-separated arguments on that line? If so, OK, I'll get on that.

Glad you like the changes.

**Pull request merged**
