### PR TITLE
Add tests/max-length

### PR DESCRIPTION
**Pull request by chubin**
Add `tests/max-length` testing length of cheat sheets comment lines.
Can be used interactively:

```
    $ tests/max-length
```

### CODE REVIEW

**Comment by terminalforlife** [comment]
I think I'm missing something. Why are you sending yourself PRs?

**Comment by chubin** [comment]
Actually, the original idea was to open this PR and give it to your for review, but for that you need to be a collaborator in this project. I tried to add you as a collaborator, but you didn't accept the invitation, so I decided that there should be some reasons for that, so I merged the pull-request.

Also, another quite typical reason to open pull-requests is to make the automatic CI checks be automatically executed (it is irrelevant in this repository though, because we have no automatic CI checks currently).

**Comment by terminalforlife** [comment]
Oooh! That makes sense. Thanks for explaining. Regarding the collaborator thing, see [this](https://github.com/chubin/cheat.sheets/issues/101#issuecomment-725785886) link.

**Comment by chubin** [comment]
Oh, sorry, I missed this part. I am not sure that I understood what you meant about anonymity, because I didn’t think that it could be somehow affected with it. I think, the most important change is that you can make merges and be added as a reviewer to pull-requests

To say the truth I don’t understand why GitHub doesn’t allow to invite someone for a review if he is not a collaborator, but it is ok, one can use mentions instead

**Pull request merged**
