### PR TITLE
Started addition of C++ sheet & some python topics

### PR DESCRIPTION
**Pull request by lepatrick714**
This is just a start. Please let me know if I'm missing something. I can add more over the course of the week! 

I'll submit a new cheat sheet tonight to chubin/cheat.sh.

### CODE REVIEW

**Comment by chubin** [comment]
Hey! That's cool.

Some ideas:

should you add may be:

* lambda functions (python)
* recursion (python)

**Comment by lepatrick714** [comment]
Dope! I'll submit another pull request for those features. 

Are the new C++ cheats intergeated with cheat.sh?

**Comment by chubin** [comment]
Yes, have you checked them? Try something like:

```
curl cheat.sh/c++
curl cheat.sh/c++/func
```

etc.

`:learn` is not (yet) active, because I haven't written the c++ adapter for _learnxiny_, but I will do it soon (tomorrow?)

**Comment by lepatrick714** [comment]
Sounds great. I'll check them in tonight. Let me know if you want any help with that.

**Pull request merged**
